// Dummy data for student management
export const dummyStudents = [
  {
    id: 1,
    fullName: "Nguyễn Văn An",
    dateOfBirth: "1995-03-15",
    phone: "0901234567",
    email: "nguyenvanan@gmail.com",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    learningNeeds: "Giao tiếp cơ bản",
    courseInterest: "TOEIC 450-650",
    status: "Đang học",
    class: "TOEIC-A1",
    registrationDate: "2024-01-15",
    lastContact: "2024-09-20",
    notes: "Học viên chăm chỉ, tiến bộ tốt"
  },
  {
    id: 2,
    fullName: "Trần Thị Bình",
    dateOfBirth: "1998-07-22",
    phone: "0912345678",
    email: "tranthibinh@yahoo.com",
    address: "456 Đường XYZ, Quận 3, TP.HCM",
    learningNeeds: "IELTS Academic",
    courseInterest: "IELTS 6.0-7.0",
    status: "Chờ lớp",
    class: "IELTS-B2",
    registrationDate: "2024-08-10",
    lastContact: "2024-09-18",
    notes: "Cần hỗ trợ thêm về writing"
  },
  {
    id: 3,
    fullName: "Lê Minh Cường",
    dateOfBirth: "1992-11-08",
    phone: "0923456789",
    email: "leminhcuong@gmail.com",
    address: "789 Đường DEF, Quận 7, TP.HCM",
    learningNeeds: "Business English",
    courseInterest: "BEC Vantage",
    status: "Đã hoàn thành",
    class: "BEC-C1",
    registrationDate: "2024-02-20",
    lastContact: "2024-09-15",
    notes: "Hoàn thành khóa học với điểm cao"
  },
  {
    id: 4,
    fullName: "Phạm Thị Dung",
    dateOfBirth: "2000-05-12",
    phone: "0934567890",
    email: "phamthidung@gmail.com",
    address: "321 Đường GHI, Quận 10, TP.HCM",
    learningNeeds: "Giao tiếp hàng ngày",
    courseInterest: "General English",
    status: "Tạm dừng",
    class: "GE-A2",
    registrationDate: "2024-06-05",
    lastContact: "2024-09-10",
    notes: "Tạm dừng do công việc"
  },
  {
    id: 5,
    fullName: "Hoàng Văn Em",
    dateOfBirth: "1997-09-30",
    phone: "0945678901",
    email: "hoangvanem@outlook.com",
    address: "654 Đường JKL, Quận Bình Thạnh, TP.HCM",
    learningNeeds: "TOEFL iBT",
    courseInterest: "TOEFL 80-100",
    status: "Đang học",
    class: "TOEFL-B1",
    registrationDate: "2024-07-15",
    lastContact: "2024-09-25",
    notes: "Cần cải thiện kỹ năng listening"
  },
  {
    id: 6,
    fullName: "Võ Thị Phương",
    dateOfBirth: "1994-12-03",
    phone: "0956789012",
    email: "vothiphuong@gmail.com",
    address: "987 Đường MNO, Quận Tân Bình, TP.HCM",
    learningNeeds: "IELTS General",
    courseInterest: "IELTS 5.5-6.5",
    status: "Chờ lớp",
    class: "IELTS-A2",
    registrationDate: "2024-09-01",
    lastContact: "2024-09-28",
    notes: "Mới đăng ký, chờ xếp lớp"
  },
  {
    id: 7,
    fullName: "Đặng Minh Giang",
    dateOfBirth: "1996-04-18",
    phone: "0967890123",
    email: "dangminhgiang@gmail.com",
    address: "147 Đường PQR, Quận Phú Nhuận, TP.HCM",
    learningNeeds: "Cambridge English",
    courseInterest: "FCE",
    status: "Đang học",
    class: "FCE-B2",
    registrationDate: "2024-05-20",
    lastContact: "2024-09-22",
    notes: "Học viên xuất sắc, có thể thi sớm"
  },
  {
    id: 8,
    fullName: "Bùi Thị Hoa",
    dateOfBirth: "1999-08-25",
    phone: "0978901234",
    email: "buithihoa@gmail.com",
    address: "258 Đường STU, Quận Gò Vấp, TP.HCM",
    learningNeeds: "Giao tiếp cơ bản",
    courseInterest: "General English",
    status: "Đã hoàn thành",
    class: "GE-A1",
    registrationDate: "2024-03-10",
    lastContact: "2024-09-12",
    notes: "Hoàn thành khóa cơ bản, có thể học tiếp"
  }
];

export const courseOptions = [
  { value: "TOEIC 450-650", label: "TOEIC 450-650" },
  { value: "TOEIC 650-850", label: "TOEIC 650-850" },
  { value: "IELTS 5.0-6.0", label: "IELTS 5.0-6.0" },
  { value: "IELTS 6.0-7.0", label: "IELTS 6.0-7.0" },
  { value: "IELTS 7.0-8.0", label: "IELTS 7.0-8.0" },
  { value: "TOEFL 60-80", label: "TOEFL 60-80" },
  { value: "TOEFL 80-100", label: "TOEFL 80-100" },
  { value: "General English", label: "General English" },
  { value: "Business English", label: "Business English" },
  { value: "BEC Vantage", label: "BEC Vantage" },
  { value: "FCE", label: "FCE" },
  { value: "CAE", label: "CAE" }
];

export const statusOptions = [
  { value: "Chờ lớp", label: "Chờ lớp" },
  { value: "Đang học", label: "Đang học" },
  { value: "Tạm dừng", label: "Tạm dừng" },
  { value: "Đã hoàn thành", label: "Đã hoàn thành" },
  { value: "Đã hủy", label: "Đã hủy" }
];

export const classOptions = [
  { value: "TOEIC-A1", label: "TOEIC-A1" },
  { value: "TOEIC-A2", label: "TOEIC-A2" },
  { value: "TOEIC-B1", label: "TOEIC-B1" },
  { value: "IELTS-A1", label: "IELTS-A1" },
  { value: "IELTS-A2", label: "IELTS-A2" },
  { value: "IELTS-B1", label: "IELTS-B1" },
  { value: "IELTS-B2", label: "IELTS-B2" },
  { value: "IELTS-C1", label: "IELTS-C1" },
  { value: "TOEFL-A1", label: "TOEFL-A1" },
  { value: "TOEFL-A2", label: "TOEFL-A2" },
  { value: "TOEFL-B1", label: "TOEFL-B1" },
  { value: "TOEFL-B2", label: "TOEFL-B2" },
  { value: "GE-A1", label: "GE-A1" },
  { value: "GE-A2", label: "GE-A2" },
  { value: "GE-B1", label: "GE-B1" },
  { value: "BEC-A2", label: "BEC-A2" },
  { value: "BEC-B1", label: "BEC-B1" },
  { value: "BEC-B2", label: "BEC-B2" },
  { value: "BEC-C1", label: "BEC-C1" },
  { value: "FCE-A2", label: "FCE-A2" },
  { value: "FCE-B1", label: "FCE-B1" },
  { value: "FCE-B2", label: "FCE-B2" }
];
