# Generated by Django 5.0.2 on 2025-09-03 10:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
        ('khoahocs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyKhoaHoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('phan_tram_hoan_thanh', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm hoàn thành')),
                ('trang_thai', models.CharField(choices=[('dang_ky', 'Đã đăng ký'), ('dang_hoc', 'Đang học'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Hủy')], default='dang_ky', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hocvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học viên', limit_choices_to={'role__role_name': 'student'})),
                ('khoahoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoahocs.khoahoc', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Đăng ký khóa học',
                'verbose_name_plural': 'Đăng ký khóa học',
                'db_table': 'erp_enrollment',
                'ordering': ['-ngay_dang_ky'],
                'unique_together': {('hocvien', 'khoahoc')},
            },
        ),
    ]
