# Generated by Django 5.0.2 on 2025-10-08 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khoahocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ten', models.CharField(max_length=100, verbose_name='Tên lớp học')),
                ('giang_vien', models.CharField(max_length=100, verbose_name='Giảng viên')),
                ('phong_hoc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng học')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('trang_thai', models.CharField(choices=[('mo', 'Mở'), ('dang_hoc', 'Đang học'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Hủy')], default='mo', max_length=20, verbose_name='Trạng thái')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoahocs.khoahoc', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'erp_classes',
                'ordering': ['-created_at'],
            },
        ),
    ]
