# Generated by Django 5.0.2 on 2025-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lophocs', '0002_remove_lophoc_giang_vien_lophoc_giang_vien_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lophoc',
            old_name='giang_vien_id',
            new_name='giang_vien',
        ),
        migrations.AddField(
            model_name='lophoc',
            name='so_hoc_vien_toi_da',
            field=models.IntegerField(default=20, verbose_name='Số học viên tối đa'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ mở lớp', 'Chờ mở lớp'), ('Đang học', 'Đang học'), ('Tạm dừng', 'Tạm dừng'), ('Đã kết thúc', 'Đã kết thúc'), ('Đã hủy', 'Đã hủy')], default='Chờ mở lớp', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
