# Generated by Django 5.0.2 on 2025-10-08 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hocviens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trang_thai', models.CharField(choices=[('co_mat', 'Có mặt'), ('vang_co_phep', 'Vắng có phép'), ('vang_khong_phep', 'Vắng không phép')], default='co_mat', max_length=20, verbose_name='Trạng thái điểm danh')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocviens.hocvien', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'db_table': 'erp_attendances',
                'ordering': ['-created_at'],
            },
        ),
    ]
