# Generated by Django 5.0.2 on 2025-10-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diemdanhs', '0001_initial'),
        ('lichhocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemdanh',
            name='lich_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lichhocs.lichhoc', verbose_name='Lịch học'),
        ),
        migrations.AlterUniqueTogether(
            name='diemdanh',
            unique_together={('lich_hoc', 'hoc_vien')},
        ),
    ]
