# Generated by Django 5.0.2 on 2025-11-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diemdanhs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemdanh',
            name='thoi_gian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian điểm danh'),
        ),
    ]
