# Generated by Django 5.0.2 on 2025-09-03 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('nguoi_nhan', models.CharField(choices=[('tatca', 'Tất cả'), ('hocvien', 'Học viên'), ('nhanvien', 'Nhân viên'), ('user', 'Người dùng cụ thể')], default='tatca', max_length=20, verbose_name='Người nhận')),
                ('trang_thai', models.CharField(choices=[('moi', 'Mới'), ('dang_gui', 'Đang gửi'), ('da_gui', 'Đã gửi'), ('huy_bo', 'Hủy bỏ')], default='moi', max_length=20, verbose_name='Trạng thái')),
                ('loai_thong_bao', models.CharField(choices=[('thong_bao', 'Thông báo'), ('canh_bao', 'Cảnh báo'), ('thong_tin', 'Thông tin'), ('khac', 'Khác')], default='thong_bao', max_length=20, verbose_name='Loại thông báo')),
                ('user', models.ForeignKey(blank=True, help_text='Chỉ cần thiết khi chọn "Người dùng cụ thể"', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng cụ thể')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'erp_notifications',
                'ordering': ['-ngay_gui'],
            },
        ),
    ]
