# Generated by Django 5.0.2 on 2025-10-08 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LichHoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngay_hoc', models.DateField(verbose_name='Ngày học')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('phong_hoc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng học')),
                ('noi_dung', models.TextField(blank=True, null=True, verbose_name='Nội dung buổi học')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'db_table': 'erp_schedules',
                'ordering': ['ngay_hoc', 'gio_bat_dau'],
            },
        ),
    ]
