# Generated by Django 5.0.2 on 2025-10-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lichhocs', '0001_initial'),
        ('lophocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhoc',
            name='lop_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lophocs.lophoc', verbose_name='Lớp học'),
        ),
        migrations.AlterUniqueTogether(
            name='lichhoc',
            unique_together={('lop_hoc', 'ngay_hoc', 'gio_bat_dau')},
        ),
    ]
