# Generated by Django 5.0.2 on 2025-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lichhocs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhoc',
            name='ngay_hoc',
            field=models.CharField(max_length=16),
        ),
    ]
