# Generated by Django 5.0.2 on 2025-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lichhocs', '0003_alter_lichhoc_ngay_hoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhoc',
            name='lophocid',
            field=models.UUIDField(blank=True, null=True, verbose_name='LopHoc ID'),
        ),
    ]
