# Generated by Django 5.0.2 on 2025-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lichhocs', '0004_lichhoc_lophocid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhoc',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
    ]
