# Generated by Django 5.0.2 on 2025-09-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='erp_users',
        ),
    ]
