# Generated by Django 5.0.2 on 2025-10-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('giangvien', 'Giảng viên'), ('academic_staff', 'Nhân viên Học vụ'), ('sales_staff', 'Nhân viên Tư vấn'), ('finance_staff', 'Nhân viên Tài chính')], max_length=20, verbose_name='Vai trò'),
        ),
    ]
