# Generated by Django 5.0.2 on 2025-09-26 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '__first__'),
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='role.role', verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sdt',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ', regex='^(\\+84|84|0)?[1-9]\\d{8}$')], verbose_name='Số điện thoại'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
