# Generated by Django 5.0.x on 2025-09-24
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('users', '0001_initial'),
        ('privilege', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('module', models.CharField(max_length=100, verbose_name='Module', help_text='user_mgmt, crm, course_mgmt, finance, reports, ...')),
                ('raci_role', models.CharField(max_length=2, blank=True, null=True, verbose_name='RACI', help_text='A, R, C, I')),
                ('role', models.ForeignKey(to='role.Role', on_delete=models.CASCADE, verbose_name='Vai trò')),
                ('privilege', models.ForeignKey(to='privilege.Privilege', on_delete=models.CASCADE, verbose_name='Đặc quyền')),
            ],
            options={
                'verbose_name': 'Quyền vai trò',
                'verbose_name_plural': 'Quyền vai trò',
                'db_table': 'erp_role_privileges',
                'unique_together': {('role', 'privilege', 'module')},
            },
        ),
    ]
