# Generated by Django 5.0.2 on 2025-09-03 10:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('sdt', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ', regex='^(\\+84|84|0)?[1-9]\\d{8}$')], verbose_name='Số điện thoại')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('trang_thai_hoc_phi', models.CharField(choices=[('dadong', 'Đã đóng'), ('conno', 'Còn nợ'), ('chuadong', 'Chưa đóng')], default='chuadong', max_length=20, verbose_name='Trạng thái học phí')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': 'Học viên',
                'db_table': 'erp_students',
                'ordering': ['-created_at'],
            },
        ),
    ]
