# Generated by Django 5.0.2 on 2025-11-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocviens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
    ]
