# Generated by Django 5.0.2 on 2025-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocviens', '0002_hocvien_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien',
            name='nhu_cau_hoc',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
