# Generated by Django 5.0.2 on 2025-11-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocviens', '0003_hocvien_nhu_cau_hoc'),
        ('khoahocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien',
            name='khoa_hoc_quan_tam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='khoahocs.khoahoc', verbose_name='Khóa học quan tâm'),
        ),
    ]
