# Generated by Django 5.0.2 on 2025-11-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocviens', '0004_hocvien_khoa_hoc_quan_tam'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien',
            name='concern_level',
            field=models.CharField(blank=True, choices=[('moi', 'Mới'), ('quan_tam', 'Quan Tâm'), ('nong', 'Nóng'), ('mat', 'Mất')], max_length=16, null=True, verbose_name='Mức độ quan tâm'),
        ),
        migrations.AddField(
            model_name='hocvien',
            name='created_as_lead',
            field=models.BooleanField(default=False, verbose_name='Tạo như lead'),
        ),
        migrations.AddField(
            model_name='hocvien',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='Đã chuyển đổi từ lead'),
        ),
        migrations.AddField(
            model_name='hocvien',
            name='sourced',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nguồn'),
        ),
    ]
