# Generated by Django 5.0.2 on 2025-11-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocviens', '0005_hocvien_concern_level_hocvien_created_as_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocvien',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
    ]
