# Generated by Django 5.0.2 on 2025-11-12 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocviens', '0006_alter_hocvien_ngay_sinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung liên hệ')),
                ('hoc_vien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_note', to='hocviens.hocvien', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Ghi chú liên hệ',
                'verbose_name_plural': 'Ghi chú liên hệ',
                'db_table': 'erp_lead_contact_notes',
            },
        ),
    ]
