# Generated by Django 5.0.2 on 2025-09-03 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền (VNĐ)')),
                ('ngay_dong', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đóng')),
                ('hinh_thuc', models.CharField(choices=[('tienmat', 'Tiền mặt'), ('chuyenkhoan', 'Chuyển khoản'), ('the', 'Thẻ')], max_length=20, verbose_name='Hình thức thanh toán')),
                ('so_bien_lai', models.CharField(max_length=50, unique=True, verbose_name='Số biên lai')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hocvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học viên', limit_choices_to={'role__role_name': 'student'})),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'erp_payments',
                'ordering': ['-ngay_dong'],
            },
        ),
    ]
