# Generated by Django 5.0.2 on 2025-11-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanhtoans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhtoan',
            name='trang_thai',
            field=models.CharField(choices=[('pending', 'Chưa thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán')], default='pending', max_length=16, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='hinh_thuc',
            field=models.CharField(blank=True, choices=[('tienmat', 'Tiền mặt'), ('chuyenkhoan', 'Chuyển khoản'), ('the', 'Thẻ')], max_length=20, null=True, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='ngay_dong',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đóng'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='so_bien_lai',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số biên lai'),
        ),
    ]
