# Generated by Django 5.0.2 on 2025-09-03 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamSocHocVien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loai_cham_soc', models.CharField(choices=[('tuvan', 'Tư vấn'), ('theodoi', 'Theo dõi'), ('hoidap', 'Hỏi đáp'), ('khac', 'Khác')], default='tuvan', max_length=20, verbose_name='Loại chăm sóc')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('ngay', models.DateTimeField(auto_now_add=True, verbose_name='Ngày chăm sóc')),
                ('trang_thai', models.CharField(choices=[('moi', 'Mới'), ('dang_xu_ly', 'Đang xử lý'), ('hoan_thanh', 'Hoàn thành'), ('dong', 'Đóng')], default='moi', max_length=20, verbose_name='Trạng thái')),
                ('attachments', models.JSONField(blank=True, null=True, verbose_name='Tệp đính kèm')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hocvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học viên', limit_choices_to={'role__role_name': 'student'}, related_name='chamsoc_hocvien_set')),
                ('nhanvien', models.ForeignKey(blank=True, limit_choices_to={'role': 'nhanvien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên chăm sóc', related_name='chamsoc_nhanvien_set')),
            ],
            options={
                'verbose_name': 'Chăm sóc học viên',
                'verbose_name_plural': 'Chăm sóc học viên',
                'db_table': 'erp_care_logs',
                'ordering': ['-ngay'],
            },
        ),
    ]
