# Generated by Django 5.0.x on 2025-09-24
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('privilege_name', models.CharField(max_length=50, unique=True, verbose_name='Tên đặc quyền', help_text='read, write, update, delete, execute')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Đặc quyền',
                'verbose_name_plural': 'Đặc quyền',
                'db_table': 'erp_privileges',
            },
        ),
    ]
