services:
  db:
    image: postgres:16
    container_name: crm-db
    env_file:
      - .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: crm-api
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: /entrypoint.sh  # tự động detect prod -> chạy gunicorn
    restart: always  # tự khởi động lại nếu container bị crash

volumes:
  pgdata:
