services:
  db:
    image: postgres:16
    container_name: crm-db
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: crm-api
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /entrypoint.sh

volumes:
  pgdata:
