# Generated by Django 5.0.2 on 2025-09-03 10:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ten', models.CharField(max_length=200, verbose_name='Tên khóa học')),
                ('lich_hoc', models.CharField(max_length=100, verbose_name='Lịch học')),
                ('giang_vien', models.CharField(max_length=100, verbose_name='Giảng viên')),
                ('so_buoi', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số buổi học')),
                ('hoc_phi', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Học phí')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('trang_thai', models.CharField(choices=[('mo', 'Mở'), ('dong', 'Đóng'), ('hoan_thanh', 'Hoàn thành')], default='mo', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'db_table': 'erp_courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
